import Head from "next/head";
import About from "../components/About/About";

import NavBar from "../components/Navbar/NavBar";
import Slider from "../components/Slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />

        <Slider />

        <About></About>
      </main>
    </>
  );
}
